export const regionsData = {
  "Toshkent shahri": [
    "Bektemir",
    "Chilonzor",
    "Mirzo Ulug'bek",
    "Mirobod",
    "Olmazor",
    "Sergeli",
    "Shayxontoxur",
    "Uchtepa",
    "Yakkasaroy",
    "Yashnobod",
    "Yunusobod"
  ],
  "Toshkent viloyati": [
    "Angren",
    "Bekobod",
    "Bo'ka",
    "Bo'stonliq",
    "Chinoz",
    "Oqqo'rg'on",
    "Ohangaron",
    "Parkent",
    "Piskent",
    "Qibray",
    "Quyi Chirchiq",
    "O'rta Chirchiq",
    "Yuqori Chirchiq",
    "Zangiota"
  ],
  "Andijon": [
    "Andijon",
    "Asaka",
    "Baliqchi",
    "Bo'z",
    "Buloqboshi",
    "Jalolquduq",
    "Xo'jaobod",
    "Izboskan",
    "Marxamat",
    "Oltinko'l",
    "Paxtaobod",
    "Qo'rg'ontepa",
    "Shahrixon",
    "Ulug'nor",
    "Xonobod"
  ],
  "Buxoro": [
    "Buxoro",
    "Kogon",
    "G'ijduvon",
    "Jondor",
    "Olot",
    "Peshku",
    "Qorako'l",
    "Qorovulbozor",
    "Romitan",
    "Shofirkon",
    "Vobkent"
  ],
  "Farg'ona": [
    "Farg'ona",
    "Beshariq",
    "Bog'dod",
    "Buvayda",
    "Dang'ara",
    "Furqat",
    "Oltiariq",
    "O'zbekiston",
    "Qo'qon",
    "Qo'shtepa",
    "Quva",
    "Rishton",
    "So'x",
    "Toshloq",
    "Uchko'prik",
    "Yozyovon"
  ],
  "Jizzax": [
    "Jizzax",
    "Arnasoy",
    "Baxmal",
    "Do'stlik",
    "Forish",
    "G'allaorol",
    "Sharof Rashidov",
    "Mirzacho'l",
    "Paxtakor",
    "Yangiobod",
    "Zomin",
    "Zafarobod"
  ],
  "Qashqadaryo": [
    "Qarshi",
    "Chiroqchi",
    "Dehqonobod",
    "G'uzor",
    "Kasbi",
    "Kitob",
    "Koson",
    "Mirishkor",
    "Muborak",
    "Nishon",
    "Qamashi",
    "Shahrisabz",
    "Yakkabog'"
  ],
  "Navoiy": [
    "Navoiy",
    "Konimex",
    "Xatirchi",
    "Karmana",
    "Qiziltepa",
    "Navbahor",
    "Nurota",
    "Tomdi",
    "Uchquduq"
  ],
  "Namangan": [
    "Namangan",
    "Chortoq",
    "Chust",
    "Kosonsoy",
    "Mingbuloq",
    "Norin",
    "Pop",
    "To'raqo'rg'on",
    "Uchqo'rg'on",
    "Uychi",
    "Yangiqo'rg'on"
  ],
  "Samarqand": [
    "Samarqand",
    "Bulung'ur",
    "Ishtixon",
    "Jomboy",
    "Kattaqo'rg'on",
    "Narpay",
    "Nurobod",
    "Oqdaryo",
    "Paxtachi",
    "Payariq",
    "Pastdarg'om",
    "Qo'shrabot",
    "Samarqand",
    "Toyloq",
    "Urgut"
  ],
  "Surxondaryo": [
    "Termiz",
    "Angor",
    "Boysun",
    "Denov",
    "Jarqo'rg'on",
    "Qiziriq",
    "Qo'mqo'rg'on",
    "Muzrabot",
    "Oltinsoy",
    "Sariosiyo",
    "Sherobod",
    "Sho'rchi",
    "Uzun"
  ],
  "Sirdaryo": [
    "Guliston",
    "Boyovut",
    "Mirzaobod",
    "Oqoltin",
    "Sardoba",
    "Sayxunobod",
    "Sirdaryo",
    "Xovos"
  ],
  "Xorazm": [
    "Urganch",
    "Bog'ot",
    "Gurlan",
    "Xazorasp",
    "Xonqa",
    "Qo'shko'pir",
    "Shovot",
    "Urganch",
    "Yangiariq",
    "Yangibozor"
  ],
  "Qoraqalpog'iston": [
    "Nukus",
    "Amudaryo",
    "Beruniy",
    "Chimboy",
    "Ellikqal'a",
    "Kegeyli",
    "Mo'ynoq",
    "Nukus",
    "Qonliko'l",
    "Qorao'zak",
    "Qo'ng'irot",
    "Shumanay",
    "Taxtako'pir",
    "To'rtko'l",
    "Xo'jayli"
  ]
};

export const regions = Object.keys(regionsData);
